Repository folloca/Server-Backend, pull requests merged in 2023-05, with the labels that each got.

#74 [feat] #72 - Add proposal edit and delete API
  src/controllers/proposals.controller.ts
  src/dto/req/update-proposal.dto.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/image.repository.ts
  src/repositories/proposal.repository.ts
  src/services/proposals.service.ts
Labels: Feature🚀

#76 [feat] #73 - Profile lookup
  .gitignore
  src/controllers/users.controller.ts
  src/database/entities/estate-like.entity.ts
  src/database/entities/linking-like.entity.ts
  src/database/entities/linking-request.entity.ts
  src/database/entities/linking.entity.ts
  src/database/entities/opinion.entity.ts
  src/database/entities/proposal-like.entity.ts
  src/dto/res/get-linkings-res.dto.ts
  src/dto/res/get-proposal-res.dto.ts
  src/dto/res/linking-request-res.dto.ts
  src/dto/res/opinion-res.dto.ts
  src/repositories/estate.repository.ts
  src/repositories/linking.repository.ts
  src/repositories/proposal.repository.ts
  src/services/users.service.ts
Labels: Feature🚀

#79 [feat] #78 - Add opinion write API
  src/controllers/proposals.controller.ts
  src/database/entities/opinion.entity.ts
  src/repositories/proposal.repository.ts
  src/services/proposals.service.ts
Labels: Feature🚀

#81 [estates] #80 - Add proposal list response data for single estate search
  src/dto/res/single-estate-proposal-list.dto.ts
  src/repositories/proposal.repository.ts
  src/services/estates.service.ts
Labels: Feature🚀

#83 [feat] #82 - Add single proposal detail search API
  src/controllers/estates.controller.ts
  src/controllers/proposals.controller.ts
  src/dto/res/proposal-detail-res.dto.ts
  src/dto/res/proposal-numbering-data.dto.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/image.repository.ts
  src/repositories/proposal.repository.ts
  src/services/proposals.service.ts
Labels: Feature🚀

#85 [fix] #84 - Update user profile dashboard
  src/controllers/users.controller.ts
  src/custom/pipe/get-user-id.pipe.ts
Labels: Fix🛠️

#87 [feat] #86 - Add trending proposal list search API
  src/controllers/proposals.controller.ts
  src/dto/res/trending-proposal-list.dto.ts
  src/repositories/proposal.repository.ts
  src/services/proposals.service.ts
Labels: Feature🚀

#89 [feat] #88 - Add search api
  src/controllers/searches.controller.ts
  src/database/entities/hash-tag.entity.ts
  src/modules/searches.module.ts
  src/repositories/hash-tag.repository.ts
  src/services/searches.service.ts
Labels: Feature🚀

#92 [fix] #90 - Fix API responses and image save
  src/controllers/users.controller.ts
  src/database/entities/user.entity.ts
  src/dto/res/get-estate-res.dto.ts
  src/dto/res/new-user-res.dto.ts
  src/repositories/user.repository.ts
  src/services/auth.service.ts
  src/services/estates.service.ts
  src/services/proposals.service.ts
Labels: Enhancement💪, Fix🛠️
