Repository folloca/Server-Backend, pull requests merged in 2023-04, with the labels that each got.

#50 [feat] #49 - Apply userId custom pipe and middleware
  src/custom/pipe/get-user-id.pipe.ts
  src/middleware/multer-user-id.middleware.ts
  src/modules/estates/dto/req/create-estate.dto.ts
  src/modules/estates/estates.controller.ts
  src/modules/estates/estates.module.ts
  src/modules/estates/estates.service.ts
  src/modules/users/dto/req/update-userinfo-req.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/repositories/estate.repository.ts
  src/repositories/user.repository.ts
Labels: Feature🚀

#52 [feat] #51 - Add delete estate API
  src/database/entities/estate.entity.ts
  src/modules/estates/estates.controller.ts
  src/modules/estates/estates.service.ts
  src/repositories/estate.repository.ts
Labels: Feature🚀

#55 [build] #54 - Redesign directory architecture
  src/auth/google.strategy.ts
  src/auth/jwt.guard.ts
  src/auth/jwt.payload.ts
  src/auth/jwt.strategy.ts
  src/auth/kakao.strategy.ts
  src/auth/refresh.guard.ts
  src/auth/refresh.strategy.ts
  src/controllers/admin.controller.ts
  src/controllers/app.controller.ts
  src/controllers/auth.controller.ts
  src/controllers/estates.controller.ts
  src/controllers/linkings.controller.ts
  src/controllers/proposals.controller.ts
  src/controllers/searches.controller.ts
  src/controllers/users.controller.ts
  src/custom/data/nickname-keywords.ts
  src/custom/decorator/typeorm-repository.decorator.ts
  src/custom/enum/posterior-filter.enum.ts
  src/custom/enum/prior-filter.enum.ts
  src/dto/req/create-estate.dto.ts
  src/dto/req/login-req.dto.ts
  src/dto/req/oauth-signup-req.dto.ts
  src/dto/req/signup-req.dto.ts
  src/dto/req/update-userinfo-req.dto.ts
  src/dto/res/kakao-tokens-res.dto.ts
  src/dto/res/kakao-userInfo-res.dto.ts
  src/dto/res/login-res.dto.ts
  src/main.ts
  src/modules/admin.module.ts
  src/modules/admin/admin.module.ts
  src/modules/app.module.ts
  src/modules/auth.module.ts
  src/modules/estates.module.ts
  src/modules/linkings.module.ts
  src/modules/proposals.module.ts
  src/modules/searches.module.ts
  src/modules/searches/searches.module.ts
  src/modules/typeorm-repository.module.ts
  src/modules/users.module.ts
  src/repositories/admin.repository.ts
  src/repositories/estate.repository.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/linking.repository.ts
  src/repositories/proposal.repository.ts
  src/repositories/user.repository.ts
  src/services/admin.service.ts
  src/services/app.service.ts
  src/services/auth.service.ts
  src/services/estates.service.ts
  src/services/linkings.service.ts
  src/services/proposals.service.ts
  src/services/searches.service.ts
  src/services/users.service.ts
Labels: Build⛑️

#58 [feat] #56 - Add transaction process
  src/repositories/estate.repository.ts
  src/repositories/functions.ts
  src/test/.gitkeeper
Labels: Feature🚀

#61 [fix] #59 - User logout logic
  package.json
  src/config/config-template.yaml
  src/controllers/auth.controller.ts
  src/main.ts
  src/middleware/multer-user-id.middleware.ts
  src/modules/auth.module.ts
  src/services/auth.service.ts
Labels: Documentation📄, Build⛑️, Fix🛠️, Feature🚀

#62 [feat] #60 - Update estate creation API
  package.json
  src/controllers/estates.controller.ts
  src/database/entities/estate-image.entity.ts
  src/database/entities/estate-tag.entity.ts
  src/database/entities/estate.entity.ts
  src/database/entities/hash-tag.entity.ts
  src/dto/req/create-estate.dto.ts
  src/main.ts
  src/modules/estates.module.ts
  src/repositories/estate.repository.ts
  src/repositories/functions.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/image.repository.ts
  src/services/estates.service.ts
  src/utilities/multer.options.ts
Labels: Fix🛠️, Feature🚀

#64 Fix/#63 fix reissuance access token
  src/controllers/auth.controller.ts
  src/main.ts
  src/services/auth.service.ts
Labels: Fix🛠️

#66 [refactor] #65 - Replace estate redis module
  src/modules/estates.module.ts
  src/repositories/estate.repository.ts
  src/services/estates.service.ts
Labels: Fix🛠️, Refactor🛁

#68 [feat] #67 - Add estate search API
  src/controllers/estates.controller.ts
  src/custom/pipe/get-user-id.pipe.ts
  src/database/entities/estate-image.entity.ts
  src/database/entities/estate-like.entity.ts
  src/database/entities/estate-tag.entity.ts
  src/dto/res/get-estate-res.dto.ts
  src/middleware/multer-user-id.middleware.ts
  src/repositories/estate.repository.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/image.repository.ts
  src/services/estates.service.ts
Labels: Feature🚀

#70 [feat] #69 - Add proposal register API
  src/controllers/estates.controller.ts
  src/controllers/proposals.controller.ts
  src/database/entities/map-numbering.entity.ts
  src/database/entities/proposal-detail.entity.ts
  src/database/entities/proposal-image.entity.ts
  src/database/entities/proposal-tag.entity.ts
  src/database/entities/proposal.entity.ts
  src/dto/req/create-proposal.dto.ts
  src/dto/res/pre-proposal-estate-res.dto.ts
  src/modules/proposals.module.ts
  src/repositories/estate.repository.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/image.repository.ts
  src/repositories/proposal.repository.ts
  src/services/proposals.service.ts
Labels: Feature🚀

#71 [chore] #69 - Add description and response when no map image
  src/dto/req/create-proposal.dto.ts
  src/dto/res/pre-proposal-estate-res.dto.ts
Labels: Feature🚀
