Repository folloca/Server-Backend, pull requests merged in 2023-02, with the labels that each got.

#34 [fix] #33 - Update Kakao Login API
  src/database/repositories/user.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/res/kakao-userInfo-res.dto.ts
Labels: Fix🛠️

#37 [feat] #35 - Handle nickname exceptions
  src/modules/admin/admin.module.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/jwt/jwt.strategy.ts
  src/modules/estates/estates.module.ts
  src/modules/estates/estates.service.ts
  src/modules/linkings/linkings.module.ts
  src/modules/proposals/proposals.module.ts
  src/modules/searches/searches.module.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
  src/repositories/admin.repository.ts
  src/repositories/estate.repository.ts
  src/repositories/hash-tag.repository.ts
  src/repositories/linking.repository.ts
  src/repositories/proposal.repository.ts
  src/repositories/user.repository.ts
Labels: Fix🛠️, Feature🚀

#39 [feat] #36 - Add API for forgot password
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: Feature🚀

#41 [feat] #40 - Update guard
  src/main.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/jwt/jwt.guard.ts
  src/modules/estates/estates.controller.ts
  src/modules/users/users.controller.ts
Labels: Feature🚀

#43 [feat] #42 - Modify ManyToMany
  src/config/typeorm.config.ts
  src/database/entities/admin.entity.ts
  src/database/entities/banner.entity.ts
  src/database/entities/date-column.entity.ts
  src/database/entities/estate-image.entity.ts
  src/database/entities/estate-like.entity.ts
  src/database/entities/estate-tag.entity.ts
  src/database/entities/estate.entity.ts
  src/database/entities/hash-tag.entity.ts
  src/database/entities/index.ts
  src/database/entities/linking-image.entity.ts
  src/database/entities/linking-like.entity.ts
  src/database/entities/linking-request.entity.ts
  src/database/entities/linking-tag.entity.ts
  src/database/entities/linking.entity.ts
  src/database/entities/map-numbering.entity.ts
  src/database/entities/opinion.entity.ts
  src/database/entities/proposal-detail.entity.ts
  src/database/entities/proposal-image.entity.ts
  src/database/entities/proposal-like.entity.ts
  src/database/entities/proposal-tag.entity.ts
  src/database/entities/proposal.entity.ts
  src/database/entities/user.entity.ts
Labels: Fix🛠️
