Repository folloca/Server-Backend, pull requests merged in 2023-01, with the labels that each got.

#20 [feat] #19 - Add multer option
  package-lock.json
  package.json
  src/config/config-template.yaml
  src/config/typeorm.config.ts
  src/database/entities/estate-image.entity.ts
  src/database/entities/estate.entity.ts
  src/database/repositories/estate.repository.ts
  src/modules/estates/dto/req/create-estate.dto.ts
  src/modules/estates/estates.controller.ts
  src/modules/estates/estates.module.ts
  src/modules/estates/estates.service.ts
  src/utilities/multer.options.ts
Labels: Bug🪲, Feature🚀

#22 [feat] #21 - Add estate like api
  src/database/repositories/estate.repository.ts
  src/modules/estates/estates.controller.ts
  src/modules/estates/estates.service.ts
Labels: Feature🚀

#24 [feat] #23 - Fix logout API
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
Labels: Fix🛠️, Feature🚀

#27 [feat] #25 - Add like data insert process
  src/database/repositories/estate.repository.ts
  src/modules/estates/estates.controller.ts
  src/modules/estates/estates.service.ts
  src/utilities/multer.options.ts
Labels: Fix🛠️, Feature🚀

#28 [feat] #26 - Add nickname APIs
  src/database/repositories/user.repository.ts
  src/modules/users/nickname-keywords.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: Feature🚀

#30 Fix/#29 o auth(kakao) login api
  package.json
  src/config/typeorm.config.ts
  src/database/entities/user.entity.ts
  src/database/repositories/user.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/req/oAuthSignup-req.dto.ts
  src/modules/auth/dto/res/kakao-userInfo-res.dto.ts
  src/modules/auth/jwt/kakao.strategy.ts
Labels: Fix🛠️, Feature🚀

#32 [feat] #31 - Add user information APIs
  src/database/entities/user.entity.ts
  src/database/repositories/user.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/dto/req/oauth-signup-req.dto.ts
  src/modules/estates/estates.controller.ts
  src/modules/users/dto/req/update-userinfo-req.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  src/utilities/multer.options.ts
Labels: Fix🛠️, Feature🚀
